"""Migration

Revision ID: 620de48bfb7e
Revises: 541b8bf04382
Create Date: 2025-04-05 16:18:33.616698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620de48bfb7e'
down_revision: Union[str, None] = '541b8bf04382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_level_requirements', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('high_level_requirements', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('high_level_requirements', 'order')
    op.drop_column('high_level_requirements', 'requirement_text')
    op.add_column('low_level_requirements', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('low_level_requirements', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('low_level_requirements', 'tech_stack_details')
    op.drop_column('low_level_requirements', 'requirement_text')
    op.add_column('test_cases', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('test_cases', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('test_cases', 'expected_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('expected_result', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('test_cases', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('test_cases', 'name')
    op.add_column('low_level_requirements', sa.Column('requirement_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('low_level_requirements', sa.Column('tech_stack_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('low_level_requirements', 'description')
    op.drop_column('low_level_requirements', 'name')
    op.add_column('high_level_requirements', sa.Column('requirement_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('high_level_requirements', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('high_level_requirements', 'description')
    op.drop_column('high_level_requirements', 'name')
    # ### end Alembic commands ###
