"""Migration

Revision ID: 67669369e468
Revises: 7b7d975c1806
Create Date: 2025-04-06 00:45:31.457021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67669369e468'
down_revision: Union[str, None] = '7b7d975c1806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_level_requirements', sa.Column('parent_uiid', sa.String(length=255), nullable=True))
    op.add_column('low_level_requirements', sa.Column('parent_uiid', sa.String(length=255), nullable=True))
    op.add_column('test_cases', sa.Column('parent_uiid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'parent_uiid')
    op.drop_column('low_level_requirements', 'parent_uiid')
    op.drop_column('high_level_requirements', 'parent_uiid')
    # ### end Alembic commands ###
