"""Migration

Revision ID: 9706cb4e40f1
Revises: f08cae0d2f41
Create Date: 2025-04-03 14:34:52.864579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9706cb4e40f1'
down_revision: Union[str, None] = 'f08cae0d2f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('user_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_flows_id'), 'user_flows', ['id'], unique=False)
    op.create_index(op.f('ix_user_flows_project_id'), 'user_flows', ['project_id'], unique=False)
    op.create_table('high_level_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('user_flow_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_flow_id'], ['user_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_high_level_requirements_id'), 'high_level_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_high_level_requirements_user_flow_id'), 'high_level_requirements', ['user_flow_id'], unique=False)
    op.create_table('low_level_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('tech_stack_details', sa.Text(), nullable=True),
    sa.Column('high_level_requirement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['high_level_requirement_id'], ['high_level_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_low_level_requirements_high_level_requirement_id'), 'low_level_requirements', ['high_level_requirement_id'], unique=False)
    op.create_index(op.f('ix_low_level_requirements_id'), 'low_level_requirements', ['id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('low_level_requirement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['low_level_requirement_id'], ['low_level_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_low_level_requirement_id'), 'test_cases', ['low_level_requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_low_level_requirement_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_low_level_requirements_id'), table_name='low_level_requirements')
    op.drop_index(op.f('ix_low_level_requirements_high_level_requirement_id'), table_name='low_level_requirements')
    op.drop_table('low_level_requirements')
    op.drop_index(op.f('ix_high_level_requirements_user_flow_id'), table_name='high_level_requirements')
    op.drop_index(op.f('ix_high_level_requirements_id'), table_name='high_level_requirements')
    op.drop_table('high_level_requirements')
    op.drop_index(op.f('ix_user_flows_project_id'), table_name='user_flows')
    op.drop_index(op.f('ix_user_flows_id'), table_name='user_flows')
    op.drop_table('user_flows')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
