"""Migration

Revision ID: 06f7437a67be
Revises: 67669369e468
Create Date: 2025-04-06 01:01:36.650472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f7437a67be'
down_revision: Union[str, None] = '67669369e468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_high_level_requirements_user_flow_id', table_name='high_level_requirements')
    op.drop_constraint('high_level_requirements_user_flow_id_fkey', 'high_level_requirements', type_='foreignkey')
    op.drop_column('high_level_requirements', 'user_flow_id')
    op.drop_index('ix_low_level_requirements_high_level_requirement_id', table_name='low_level_requirements')
    op.drop_constraint('low_level_requirements_high_level_requirement_id_fkey', 'low_level_requirements', type_='foreignkey')
    op.drop_column('low_level_requirements', 'high_level_requirement_id')
    op.drop_index('ix_test_cases_low_level_requirement_id', table_name='test_cases')
    op.drop_constraint('test_cases_low_level_requirement_id_fkey', 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'low_level_requirement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('low_level_requirement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('test_cases_low_level_requirement_id_fkey', 'test_cases', 'low_level_requirements', ['low_level_requirement_id'], ['id'])
    op.create_index('ix_test_cases_low_level_requirement_id', 'test_cases', ['low_level_requirement_id'], unique=False)
    op.add_column('low_level_requirements', sa.Column('high_level_requirement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('low_level_requirements_high_level_requirement_id_fkey', 'low_level_requirements', 'high_level_requirements', ['high_level_requirement_id'], ['id'])
    op.create_index('ix_low_level_requirements_high_level_requirement_id', 'low_level_requirements', ['high_level_requirement_id'], unique=False)
    op.add_column('high_level_requirements', sa.Column('user_flow_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('high_level_requirements_user_flow_id_fkey', 'high_level_requirements', 'user_flows', ['user_flow_id'], ['id'])
    op.create_index('ix_high_level_requirements_user_flow_id', 'high_level_requirements', ['user_flow_id'], unique=False)
    # ### end Alembic commands ###
