"""Add requirement models

Revision ID: a1adfe599243
Revises: 6e65ded342f7
Create Date: 2025-03-27 12:12:16.641059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1adfe599243'
down_revision: Union[str, None] = '6e65ded342f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_flows_id'), 'user_flows', ['id'], unique=False)
    op.create_index(op.f('ix_user_flows_project_id'), 'user_flows', ['project_id'], unique=False)
    op.create_table('flow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('user_flow_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_flow_id'], ['user_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_steps_id'), 'flow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_flow_steps_user_flow_id'), 'flow_steps', ['user_flow_id'], unique=False)
    op.create_table('high_level_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('flow_step_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flow_step_id'], ['flow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_high_level_requirements_flow_step_id'), 'high_level_requirements', ['flow_step_id'], unique=False)
    op.create_index(op.f('ix_high_level_requirements_id'), 'high_level_requirements', ['id'], unique=False)
    op.create_table('low_level_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('tech_stack_details', sa.Text(), nullable=True),
    sa.Column('high_level_requirement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['high_level_requirement_id'], ['high_level_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_low_level_requirements_high_level_requirement_id'), 'low_level_requirements', ['high_level_requirement_id'], unique=False)
    op.create_index(op.f('ix_low_level_requirements_id'), 'low_level_requirements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_low_level_requirements_id'), table_name='low_level_requirements')
    op.drop_index(op.f('ix_low_level_requirements_high_level_requirement_id'), table_name='low_level_requirements')
    op.drop_table('low_level_requirements')
    op.drop_index(op.f('ix_high_level_requirements_id'), table_name='high_level_requirements')
    op.drop_index(op.f('ix_high_level_requirements_flow_step_id'), table_name='high_level_requirements')
    op.drop_table('high_level_requirements')
    op.drop_index(op.f('ix_flow_steps_user_flow_id'), table_name='flow_steps')
    op.drop_index(op.f('ix_flow_steps_id'), table_name='flow_steps')
    op.drop_table('flow_steps')
    op.drop_index(op.f('ix_user_flows_project_id'), table_name='user_flows')
    op.drop_index(op.f('ix_user_flows_id'), table_name='user_flows')
    op.drop_table('user_flows')
    # ### end Alembic commands ###
